# ~/config/traefik/traefik.toml

ni[global]
  checkNewVersion = true
  sendAnonymousUsage = true

[serversTransport]
  insecureSkipVerify = true

[entryPoints]
  [entryPoints.web]
    address = ":80"
    [entryPoints.web.http]
      [entryPoints.web.http.redirections]
        [entryPoints.web.http.redirections.entryPoint]
          to = "websecure"
          scheme = "https"
  [entryPoints.websecure]
    address = ":443"

[providers]
  [providers.docker]
    watch = true
    exposedByDefault = false
    swarmMode = true
    network = "web"
  [providers.file]
    watch = true
    filename = "traefik_dynamic.toml"

[api]
  insecure = false
  dashboard = true
  debug = true

# Log levels: DEBUG, INFO, WARN, ERROR, FATAL, PANIC
[log]
  level = "INFO"
  filePath = "/traefik.log"

[certificatesResolvers]
  [certificatesResolvers.letsencrypt]
    [certificatesResolvers.letsencrypt.acme]
      email = "email@example.com"
      # Commented out in production
      #caServer = "https://acme-staging-v02.api.letsencrypt.org/directory"
      storage = "acme.json"
      [certificatesResolvers.letsencrypt.acme.tlsChallenge]
